services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quarkus-network

  # Serviço para rodar a aplicação Quarkus em modo JVM
  # quarkus-app-jvm:
  #   build:
  #     context: .
  #     dockerfile: src/main/docker/Dockerfile.jvm
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - quarkus-network
  #   environment:
  #     JAVA_DEBUG: true 
  #     JAVA_DEBUG_PORT: "5005"

  # Serviço para rodar a aplicação Quarkus como uma imagem nativa
  # quarkus-app-native:
  #   build:
  #     context: .
  #     dockerfile: src/main/docker/Dockerfile.native
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - quarkus-network
  #   environment:
  #     JAVA_DEBUG: true 
  #     JAVA_DEBUG_PORT: "5005"

volumes:
  postgres_data:

networks:
  quarkus-network:
    driver: bridge
